In [2]:
import torch
torch.__version__

'2.6.0+cu124'

In [4]:
# ==============================
# 1. 텐서(Tensor) 기초
# ==============================

import torch

# 텐서 생성 방법들
a = torch.tensor([1, 2, 3])              # 리스트로부터 생성
b = torch.zeros(2, 3)                     # 0으로 채운 2x3 텐서
c = torch.ones(2, 3)                      # 1로 채운 2x3 텐서
d = torch.randn(2, 3)                     # 표준정규분포 랜덤 2x3 텐서
e = torch.arange(0, 10, 2)               # [0, 2, 4, 6, 8]
f = torch.linspace(0, 1, 5)              # 0~1 사이 균일 간격 5개

print("리스트에서 생성:", a)
print("zeros:", b)
print("ones:", c)
print("randn:", d)
print("arange:", e)
print("linspace:", f)

리스트에서 생성: tensor([1, 2, 3])
zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])
randn: tensor([[-0.8153, -0.1279, -0.3280],
        [ 0.5748, -1.0823, -0.9111]])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [5]:
# ==============================
# 2. 텐서 속성 확인
# ==============================

x = torch.randn(3, 4)

print("shape:", x.shape)          # 텐서 크기
print("dtype:", x.dtype)          # 데이터 타입
print("device:", x.device)        # 저장 위치 (cpu / cuda)
print("ndim:", x.ndim)            # 차원 수
print("numel:", x.numel())        # 전체 원소 개수

shape: torch.Size([3, 4])
dtype: torch.float32
device: cpu
ndim: 2
numel: 12


In [6]:
# ==============================
# 3. 텐서 연산
# ==============================

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# 기본 사칙연산 (element-wise)
print("덧셈:", a + b)
print("뺄셈:", a - b)
print("곱셈:", a * b)
print("나눗셈:", a / b)

# 행렬 곱셈
A = torch.randn(2, 3)
B = torch.randn(3, 4)
C = A @ B  # 또는 torch.matmul(A, B)
print("\n행렬 곱셈 결과 shape:", C.shape)

# 유용한 연산들
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("\n합계:", x.sum())
print("평균:", x.mean())
print("최댓값:", x.max())
print("최솟값:", x.min())
print("argmax:", x.argmax())  # 최댓값 인덱스

덧셈: tensor([5., 7., 9.])
뺄셈: tensor([-3., -3., -3.])
곱셈: tensor([ 4., 10., 18.])
나눗셈: tensor([0.2500, 0.4000, 0.5000])

행렬 곱셈 결과 shape: torch.Size([2, 4])

합계: tensor(10.)
평균: tensor(2.5000)
최댓값: tensor(4.)
최솟값: tensor(1.)
argmax: tensor(3)


In [7]:
# ==============================
# 4. 텐서 형태 변환 (Reshape)
# ==============================

x = torch.arange(12)
print("원본:", x, "| shape:", x.shape)

# reshape / view
y = x.reshape(3, 4)
print("\nreshape(3,4):\n", y)

z = x.reshape(2, 2, 3)
print("\nreshape(2,2,3):\n", z)

# -1은 자동 계산
w = x.reshape(4, -1)  # 4 x ? → 4 x 3
print("\nreshape(4,-1):\n", w)

# squeeze / unsqueeze
a = torch.randn(1, 3, 1)
print("\n원본 shape:", a.shape)
print("squeeze:", a.squeeze().shape)         # 크기 1인 차원 제거 → (3,)
print("unsqueeze(0):", a.squeeze().unsqueeze(0).shape)  # 0번 위치에 차원 추가 → (1,3)

원본: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) | shape: torch.Size([12])

reshape(3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

reshape(2,2,3):
 tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

reshape(4,-1):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

원본 shape: torch.Size([1, 3, 1])
squeeze: torch.Size([3])
unsqueeze(0): torch.Size([1, 3])


In [8]:
# ==============================
# 5. 인덱싱 & 슬라이싱
# ==============================

x = torch.arange(12).reshape(3, 4)
print("텐서:\n", x)

print("\n첫 번째 행:", x[0])
print("두 번째 열:", x[:, 1])
print("부분 슬라이스:\n", x[0:2, 1:3])

# Boolean 인덱싱
print("\n5보다 큰 원소:", x[x > 5])

텐서:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

첫 번째 행: tensor([0, 1, 2, 3])
두 번째 열: tensor([1, 5, 9])
부분 슬라이스:
 tensor([[1, 2],
        [5, 6]])

5보다 큰 원소: tensor([ 6,  7,  8,  9, 10, 11])


In [9]:
# ==============================
# 6. GPU로 텐서 이동
# ==============================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.randn(3, 3)
print("원래 device:", x.device)

x = x.to(device)  # GPU로 이동
print("이동 후 device:", x.device)

# GPU 텐서끼리 연산
y = torch.randn(3, 3).to(device)
z = x + y
print("결과 device:", z.device)

# 다시 CPU로 (numpy 변환 등에 필요)
z_cpu = z.cpu()
print("CPU로 복귀:", z_cpu.device)

원래 device: cpu
이동 후 device: cuda:0
결과 device: cuda:0
CPU로 복귀: cpu


In [10]:
# ==============================
# 7. Autograd (자동 미분) - 딥러닝의 핵심!
# ==============================

# requires_grad=True → 이 텐서에 대한 연산을 추적하여 기울기 계산
x = torch.tensor([2.0, 3.0], requires_grad=True)

# 간단한 연산: y = x^2 + 3x
y = x ** 2 + 3 * x
z = y.sum()  # 스칼라로 만들어야 backward 가능

print("x:", x)
print("y (x²+3x):", y)
print("z (y의 합):", z)

# 역전파 (기울기 계산)
z.backward()

# dy/dx = 2x + 3
print("\n기울기 (dy/dx = 2x+3):", x.grad)
# x=2일 때 → 2*2+3=7, x=3일 때 → 2*3+3=9

x: tensor([2., 3.], requires_grad=True)
y (x²+3x): tensor([10., 18.], grad_fn=<AddBackward0>)
z (y의 합): tensor(28., grad_fn=<SumBackward0>)

기울기 (dy/dx = 2x+3): tensor([7., 9.])


In [11]:
# ==============================
# 8. 간단한 선형회귀 직접 구현
# ==============================

import torch

# 데이터 생성: y = 3x + 1 + noise
torch.manual_seed(42)
X = torch.randn(100, 1)
y = 3 * X + 1 + 0.3 * torch.randn(100, 1)

# 파라미터 초기화
w = torch.randn(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

learning_rate = 0.1
epochs = 100

for epoch in range(epochs):
    # 순전파 (Forward)
    y_pred = X * w + b
    
    # 손실 계산 (MSE)
    loss = ((y_pred - y) ** 2).mean()
    
    # 역전파 (Backward)
    loss.backward()
    
    # 파라미터 업데이트 (경사하강법)
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
    
    # 기울기 초기화 (매우 중요!)
    w.grad.zero_()
    b.grad.zero_()
    
    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch+1:3d} | Loss: {loss.item():.4f} | w: {w.item():.4f} | b: {b.item():.4f}")

print(f"\n최종 결과: y = {w.item():.2f}x + {b.item():.2f}")
print("정답:      y = 3.00x + 1.00")

Epoch  20 | Loss: 0.0719 | w: 2.9704 | b: 1.0084
Epoch  40 | Loss: 0.0702 | w: 3.0031 | b: 1.0108
Epoch  60 | Loss: 0.0702 | w: 3.0035 | b: 1.0107
Epoch  80 | Loss: 0.0702 | w: 3.0035 | b: 1.0107
Epoch 100 | Loss: 0.0702 | w: 3.0035 | b: 1.0107

최종 결과: y = 3.00x + 1.01
정답:      y = 3.00x + 1.00


In [12]:
# ==============================
# 9. nn.Module로 모델 만들기
# ==============================

import torch
import torch.nn as nn

# 같은 데이터 사용
torch.manual_seed(42)
X = torch.randn(100, 1)
y = 3 * X + 1 + 0.3 * torch.randn(100, 1)

# 모델 정의
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)  # 입력 1개, 출력 1개
    
    def forward(self, x):
        return self.linear(x)

model = LinearModel()
print("모델 구조:", model)
print("파라미터:", list(model.parameters()))

모델 구조: LinearModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
파라미터: [Parameter containing:
tensor([[0.4801]], requires_grad=True), Parameter containing:
tensor([0.8415], requires_grad=True)]


In [13]:
# ==============================
# 10. 옵티마이저 & 손실함수로 학습
# ==============================

import torch.optim as optim

# 손실함수 & 옵티마이저
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# 학습 루프
for epoch in range(100):
    # 순전파
    y_pred = model(X)
    loss = criterion(y_pred, y)
    
    # 역전파 & 업데이트
    optimizer.zero_grad()   # 기울기 초기화
    loss.backward()         # 기울기 계산
    optimizer.step()        # 파라미터 업데이트
    
    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch+1:3d} | Loss: {loss.item():.4f}")

# 학습된 파라미터 확인
w_learned = model.linear.weight.item()
b_learned = model.linear.bias.item()
print(f"\n학습 결과: y = {w_learned:.2f}x + {b_learned:.2f}")
print("정답:      y = 3.00x + 1.00")

Epoch  20 | Loss: 0.0721
Epoch  40 | Loss: 0.0702
Epoch  60 | Loss: 0.0702
Epoch  80 | Loss: 0.0702
Epoch 100 | Loss: 0.0702

학습 결과: y = 3.00x + 1.01
정답:      y = 3.00x + 1.00


In [14]:
# ==============================
# 11. Dataset & DataLoader
# ==============================

from torch.utils.data import Dataset, DataLoader

# 커스텀 데이터셋 만들기
class SimpleDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

dataset = SimpleDataset(X, y)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

# 배치 확인
for batch_X, batch_y in dataloader:
    print("배치 X shape:", batch_X.shape)
    print("배치 y shape:", batch_y.shape)
    break  # 첫 배치만 확인

print(f"\n전체 데이터: {len(dataset)}개")
print(f"배치 크기: 16 → 총 {len(dataloader)}개 배치")

배치 X shape: torch.Size([16, 1])
배치 y shape: torch.Size([16, 1])

전체 데이터: 100개
배치 크기: 16 → 총 7개 배치


In [15]:
import torch
import numpy as np

XOR_X = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
XOR_Y = np.array([[0.0], [1.0], [1.0], [0.0]])

epoch = 5000
lr = 0.5

x = torch.FloatTensor(XOR_X)
y = torch.FloatTensor(XOR_Y)

w1 = torch.randn(2, 5, requires_grad=True)
w2 = torch.randn(5, 1, requires_grad=True)
b1 = torch.zeros(5, requires_grad=True)
b2 = torch.zeros(1, requires_grad=True)

for epoch in range(epochs):
    h1 = x @ w1 + b1
    a1 = torch.sigmoid(h1)
    h2 = a1 @ w2 + b2
    hyp = torch.sigmoid(h2)
    
    cost = (hyp - y).pow(2).sum()
    
    cost.backward()
    
    with torch.no_grad():
        w1 -= lr * w1.grad
        w2 -= lr * w2.grad
        b1 -= lr * b1.grad
        b2 -= lr * b2.grad
        
    w1.grad.zero_()
    w2.grad.zero_()
    b1.grad.zero_()
    b2.grad.zero_()
    
    if (epoch+1) % 1000 == 0:
        print(f"epoch {epoch+1:5d} | Cost: {cost.item():.6f}")
        
with torch.no_grad():
    h1 = x @ w1 + b1
    a1 = torch.sigmoid(h1)
    h2 = a1 @ w2 + b2
    pred = torch.sigmoid(h2)
    
print("\n===== XOR 예측 결과 =====")
for i in range(4):
    print(f"입력: {XOR_X[i]} → 예측: {pred[i].item():.4f} | 정답: {XOR_Y[i][0]}")


===== XOR 예측 결과 =====
입력: [0. 0.] → 예측: 0.3004 | 정답: 0.0
입력: [0. 1.] → 예측: 0.7122 | 정답: 1.0
입력: [1. 0.] → 예측: 0.5896 | 정답: 1.0
입력: [1. 1.] → 예측: 0.4116 | 정답: 0.0


Pytorch의 텐서에서 offset과 stride는 텐서가 메모리에서 데이터를 어떻게 참조하는지 설명하는 중요한 개념이다.  
1. Stride  
- 정의: 텐서의 각 차원에서 다음 원소로 이동하기 위해 메모리에서 건너뛰는 요소의 개수이다!  

In [16]:
# 예시  
x = torch.arange(12).reshape(3, 4)
print(x)
print(x.stride())
# 출력 결과 (4,1)이 나왔는데 이는 행을 바꿀때는 4칸씩 이동하고 열을 바꿀 때는 1칸씩 이동한다는 것을 의미한다.

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
(4, 1)


2. Offset  
- 정의: 텐서의 시작점이 메모리 버퍼에서 어디서부터 시작하는지를 나타낸다.
- Pytorch에서 직접적으로 offset을 제공하지는 않지만, 슬라이스된 텐서는 원본의 버퍼의 일부를 참조하여 내부적으로 offset을 관림함

In [17]:
x = torch.arange(10)
y = x[2:7]

In [18]:
x = torch.arange(12).reshape(3, 4)
y = x[:, 1:]
print(y)
print(y.stride())

tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]])
(4, 1)


## 2.2 파이토치 기초 문법  
파이토치는 텐서로 시작해서 텐서로 끝난다고 해도 과언이 아님! 따라서 텐서를 잘 다룰 수 있어야 문제 해결이 가능하고   
신경망에서 데이터 입력과 출력도 제어를 할 수 있다. 지금부터 텐서를 다루는 기초적인 문법을 알아보자!

In [19]:
# 텐서 생성 및 변환
# 텐서는 파이토치의 가장 기본이 되는 구조이다. 넘파이의 ndarray와 비슷하며 GPU에서의 연산도 가능하다.
import torch
print(torch.tensor([[1,2], [3,4]])) # 2차원 텐서 생성
print(torch.tensor([[1,2],[3,4]], device="cuda:0"))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) # dtype 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [20]:
temp = torch.tensor([[1,2], [3,4]])
print(temp.numpy())
temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


#### 텐서의 인덱스 조작  
텐서의 인덱스를 조작하는 방법은 여러 가지가 있다. 텐서의 넘파이의 ndarray를 조작하는 것과 유사하게 동작하기 때문에 배열처럼  
인덱스를 바로 지정하거나 슬라이스 등을 사용할 수 있다. 또한 텐서의 자료형은 다음과 같다.  
torch.FloatTensor: 32비트의 부동 소수점  
torch.DoubleTensor: 64비트의 부동 소수점  
torch.LongTensor: 64비트의 부호가 있는 정수  
이외에도 다양한 유형의 텐서가 있다.  
텐서의 인덱스 조작은 다음과 같다.

In [21]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0], temp[1], temp[-1])
print("----------------------")
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
----------------------
tensor([3., 4., 5.]) tensor([5., 6.])


#### 텐서 연산 및 차원 조작  
텐서는 넘파이의 ndarray처럼 다양한 수학 연산이 가능하며, GPU를 사용하면 더 빠르게 연산 할 수 있다. 참고로 텐서 간의 타입이  
다르면 연산이 불가능하다. 예를 들어, FloatTensor와 DoubleTensor 간에 사칙 연산을 수행하면 오류가 발생한다.  
다음과 같이 벡터 두 개를 생성하여 사칙 연산을 할 수 있다.

In [22]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w-v)

tensor([2, 2, 3])


텐서의 차원을 조작해 보자! 텐서의 차원에 대한 문제는 신경망에서 자주 다루어지므로 상당히 중요하다.  
텐서의 차원을 변경하는 가장 대표적인 방법은 view를 사용하는 것 이다. 이외에도 tensor를 결합하는   
stack, cat과 차원을 교환하는 t, transpose도 사용된다. view는 넘파이의 reshape과 유사하며 cat은  
다른 길이의 텐서를 하나로 병합할 때 사용한다. 또한, transpose는 행렬의 전치외에도 차원의 순서를  
변경할 때도 사용된다.  
텐서의 차원을 조작하는 코드는 다음과 같다. 

In [23]:
temp = torch.tensor([[1,2], [3,4]])
def linefunc():
    print('--------------------')
print(temp.shape)
linefunc()
print(temp.view(4,1)) # 2x2 행렬을 4x1로 변형
linefunc()
print(temp.view(-1)) # 2x2 행렬을 1차원 벡터로 변형
linefunc()
print(temp.view(1,-1)) # -1은 (1, ?)와 같은 의미로 다른 차원으로부터 해당 값을 유추하겠다는 것이다. temp의 원소 개수(2x2=4)를 유지한 채 (1, ?)의 형태를 만족해야 하므로 (1, 4)가 된다.
linefunc()
print(temp.view(-1,1)) # 앞에서 마찬가지로 (?, 1)와 같은 의미로 원소 개수를 유지한 채 (?, 1)을 만족해야 하므로 4x1이 된다.

torch.Size([2, 2])
--------------------
tensor([[1],
        [2],
        [3],
        [4]])
--------------------
tensor([1, 2, 3, 4])
--------------------
tensor([[1, 2, 3, 4]])
--------------------
tensor([[1],
        [2],
        [3],
        [4]])


#### 데이터 준비  
데이터 호출에는 파이썬 라이브러리를 이용하는 방법과 파이토치에서 제공하는 데이터를 이용하는 방법이 있다.  
데이터가 이미지일 경우 즉, 이미지 모델을 사용해야 할 경우에는 분산된 파일에서 데이터를 읽은 후 전처리를 하고  
배치 단위로 분할하여 처리한다. 데이터가 텍스트일 경우(텍스트 모델을 사용해야 할 경우) 임베딩 과정을 거쳐 서로  
다른 길이의 시퀀스를 배치 단위로 분할하여 처리한다.  

##### 단순한게 파일을 불러와서 사용  
판다스 라이브러리를 이용하여 JSON, PDF, CSV 등의 파일을 불러오는 방벙이 있다. 데이터가 복잡하지 않은 형태라면  
단순하고 유용하게 사용될 수 있다.

###### 커스텀 데이터셋을 만들어서 사용  
딥러닝은 기본적으로 대량의 데이터를 이용하여 모델을 학습시킨다. 하지만 데이터를 한 번에 메모리에 불러와서  
훈련시키면 시간과 비용 측면에서 효율적이지 않다. 따라서 데이터를 한 번에 다 부르지 않고 조금씩 나누어 불러서  
사용하는 방식이 커스텀 데이터셋이다. 먼저 CustomDataset 클래스를 구현하기 위해서는 다음 형태를 취해야 한다.  

In [ ]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self): # ------ 필요한 변수를 선언하고, 데이터를 전처리하는 생성자 함수  
    def __len__(self): # ------ 데이터셋의 길이. 즉, 총 샘플의 수를 가져오는 함수  
    def __getitem__(self, index): # ----- 데이터셋에서 특정 데이터를 가져오는 함수(index번째 데이터를 반환하는 함수이며, 이때 반환되는 값은 텐서의 형태를 취해야 한다.)

In [25]:
import torchvision.transforms as transforms

mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0, ))
])

from torchvision.datasets import MNIST
import requests

download_root = '../chap02/data/MNIST_DATASET'

train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

###### 모델 정의  
pytorch에서 모델을 정의하기 위해서는 module을 상속한 클래스를 사용한다. 그렇다면 모델과 모듈은 무엇이 다른가?  
- 계층(layer): 모듈 또는 모듈을 구성하는 한 개의 계층으로 합성곱층, 선형계층 등이 있다.  
- 모듈(module): 한 개 이상의 계층이 모여서 구성된 것으로, 모듈이 모여 새로운 모듈을 만들 수도 있다.  
- 모델(model): 최종적으로 원하는 네트워크로, 한 개의 모듈이 모델이 될 수도 있다.  

In [26]:
# 단순 신경망을 정의하는 방법
# nn.Module을 상속받지 않는 매우 단순한 모델을 만들 때 사용한다. 구현이 쉽고 단순하다는 장점이 있다.
model = nn.Linear(in_features=1, out_features=1, bias=True)
# 이 코드는 PyTorch에서 가장 기본적인 선형(Linear) 계층(=완전연결층, fully connected layer)을 생성하는 코드입니다.

# 각 인자의 의미
# in_features=1
# 입력 특성(입력 차원)이 1개임을 의미합니다.
# (예: 입력 데이터가 [x]처럼 1차원 벡터일 때)

# out_features=1
# 출력 특성(출력 차원)이 1개임을 의미합니다.
# (예: 출력도 [y]처럼 1차원 벡터)

# bias=True
# 편향(bias) 항을 포함합니다.
# (즉, y = wx + b 형태)

# 실제 동작
# 이 계층은 입력값 x에 대해
# y = x * W^T + b
# (여기서 W는 가중치, b는 편향)
# 을 계산합니다.

#### nn.Module()을 상속하여 정의하는 방법  
pytorch에서는 nn.Module을 상속받는 모델은 기본적으로 __init__()과 forward() 함수를 포함한다. __init__()에서는 모델에서  
사용될 모듈(nn.Linear, nn.Conv2d 등), 활성화 함수를 정의하고, forward() 함수에서는 모델에서 실행되어야 하는 연산을 정의한다.  
아래는 파이토치에서 모델을 정의하는 코드이다.

In [27]:
# class MLP(Module):
#     def __init__(self, inputs):
#         super(MLP, self).__init__()
#         self.layer = Linear(inputs, 1)
#         self.activation = Sigmoid()
        
#     def forward(self, X):
#         X = self.layer(X)
#         X = self.activation(X)
#         return X

In [28]:
import torch.nn as nn

class MLP(nn.Module): # 이 클래스는 nn.Module을 상속받아 신경망 모델로 사용할 수 있다는 것!
    def __init__(self): # 이건 당연히 클래스의 생성자=초기화 함수이다! 여기서 신경망의 계층 정의
        super(MLP,self).__init__() # super를 통해서 부모 클래스=nn.Module의 초기화 함수를 호출! pytorch 모델 만들때 반드시 필요!
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )
        
        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True)
        )
        
        def forward(self, x):
            x = self.layer1(x)
            x = self.layer2(x)
            x = x.view(x.shape[0], -1)
            x = self.layer3(x)
            return x
        
model = MLP() # 모델에 대한 객체 생성

print("Printing children\n-----------------------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n-------------------------------------")
print(list(model.modules()))        

Printing children
-----------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-------------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
  

model.modules()와 model.children()
model.modules()는 모델의 네트워크에 대한 모든 노드를 반환하며, model.children()은 같은 수준의 하위 노드를 반환한다.

#### 함수로 신경망을 정의하는 방법  
Sequential을 이용하는 것과 동일하지만, 함수로 선언할 경우 변수에 저장해 놓은 계층들을 재사용할 수 있는 장점이 있다.  
하지만 모델이 복잡해지는 단점도 있다. 참고로 복잡한 모델의 경우에는 함수를 이용하는 것보다 nn.Module()을 상속받아 사용하는 것이 편리하다!  
아래 코드를 통해 확인해보자!

In [29]:
def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features=in_features, out_features=out_features, bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
    net = nn.Sequential(hidden, activation, output)
    return net

#### 모델의 파라미터 정의  
모델은 학습하기 전에 필요한 파라미터들을 정의한다. 사전에 정의할 파라미터는 다음과 같다.  
- 손실 함수: 학습하는 동안 출력과 실제 값 사이의 오차를 측정한다. 즉, $wx+b$를 계산한 값과 실제 값인 $y$의 오차를 구해서 모델의 정확성을 측정함. 아래는 대표적인 손실 함수임.  
    - BCELoss: 이진 분류를 위해 사용하는 Binary Cross Entropy임
    - CrossEntropyLoss: 다중 클래스 분류를 위해 사용함  
    - MSELoss: 회귀 모델에서 사용함 Mean Squared Error
- 옵티마이저: 데이터의 손실 함수를 바탕으로 모델의 업데이트 방법을 결정함. 다음은 Optimizer의 주요 특징이다.  
    - optimizer는 step() 메서드를 통해 전달받은 파라미터를 업데이트한다.  
    - 모델의 파라미터 별로 다른 기준을 적용시킬 수 있다.
    - torch.optim.Optimizer(params, defaults)는 모든 옵티마이저의 기본이 되는 클래스임
    - zero_grad() 메서드는 optimizer에 사용된 파라미터의 기울기를 0으로 만든다.
    - torch.optim.lr_scheduler는 에포크에 따라 학습률 조정이 가능
    - optimizer에 사용되는 종류는 아래와 같다.  
        - optim.Adadelta, optim.Adagrad, optim.SparseAdam, optim.Adamax  
        - optim.ASGD, optim.BFGS  
        - optim.RMSProp, optim.Rprop, optim.SGD  
- 학습률 스케쥴러(learning rate scheduler): 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소 즉, decay 해주는 것이다. 학습률 스케쥴러를 이용하면 학습 초기에는 빠른 학습을 진행하다가  
전역 최소점 즉, global minimum 근처에 다다르면 학습률을 줄여서 최적점을 찾아갈 수 있도록 해준다. 학습률 스케쥴러의 종류는 아래와 같다.  
    - optim.lr_schedular.LambdaLR: 람다 함수를 이용하여 그 함수의 결과를 학습률로 설정함
    - optim.lr_schedular.StepLR: 특정 단계마다 학습률을 감마 비율 만큼 감소시킨다.
    - optim.lr_schedular.MultiStepLR: StepLR과 비슷하지만 특정 단계가 아닌 지정된 에포크에만 감마 비율로 감소시킨다.
    - optim.lr_schedular.ExponentialLR: 에포크마다 이전 학습률에 감마만큼 곱한다.
    - optim.lr_schedular.CosineAnnealingLR: 학습률을 코사인 함수의 형태처럼 변화시킨다. 따라서 학습률이 커지기도 작아지기도 한다.
    - optim.lr_schedular.ReduceLROnPlateau: 학습이 잘되고 있는지 아닌지에 따라 동적으로 학습률을 변화시킬 수 있다.
- 지표(metrics): 훈련과 테스트 단계를 모니터링 함 



In [ ]:
from torch.optim import optimizer
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
schedular = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda=lambda epoch: 0.95**epoch)

for epoch in range(1, 100+1):
    for x, y in dataloader:
        optimizer.zero_grad()
        
loss_fn(model(x), y).backward()
optimizer.step()
schedular.step()

구체적인 훈련 방법에 대해 알아보자! 가장 먼저 필요한 절차가 optimizer.zero_grad() 메서드를 이용하여 기울기를 초기화하는 것이다. 파이토치는 기울기 값을 계산하기 위해 loss.backward() 메서드를  
이용하는데, 이것을 사용하면 새로운 기울기 값이 이전 기울기 값에 누적하여 계산이 된다. 이 방법은 RNN에서 모델을 구현할때 효과적이지만, 누적 계산이 필요하지 않은 모델에 대해서는 불필요한다.  
따라서 기울기 값에 대해 누적 계산이 필요하지 않을 때는 입력 값을 모델에 적용하기 전에 optimizer.zero_grad() 메서드를 호출하여 미분 값이 누적되지 않게 초기화해주어야 한다.

In [ ]:
# 이렇게 해야 오차가 중첩적으로 쌓이지 않음
for epoch in range(1000):
    yhat = model(x_train)
    loss = criterion(yhat, y_train)
    optimizer.zero_grad() # <-- 이 코드가 바로 오차를 중첩적으로 쌓이지 않게 함!
    loss.backward() # 역전파 학습
    optimizer.step() # 기울기 업데이트

In [ ]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target) # 모델을 평가하기 위해 functional.accuracy(preds, target)

In [ ]:
import torch
import torchmetrics
metric = torchmetrics.Accuracy()

n_batches = 10
for i in range(n_batches):
    preds = torch.randn(10, 5).softmax(dim=-1)
    target = torch.randint(5, (10,))
    
    acc = metric(preds, target)
    print(f"Accuracy on batch {i}: {acc}")
    
acc = metric.compute()
print(f"Accuracy on all data: {acc}")

In [ ]:
model.eval()
with torch.no_grad():
    valid_loss = 0
    
    for x, y in valid_dataloader:
        output = model(x)
        loss = F.cross_entropy(outputs, y.long().squeeze())
        valid_loss += float(loss)
        y_hat += [outputs]
        
valid_loss = valid_loss / len(valid_loader)